version: "3.3"
services:
  api_gateway:
    container_name: api_gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5001"
    volumes:
      - ./app/:/app/
  mariadb-galera-bootstrap:
    extends:
      file: docker-compose.mysql.yml
      service: mariadb-galera-bootstrap