version: '3'

services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management-alpine
        tty: true
        ports:
            - "15672:15672"
            - "5672:5672"

    mariadb-galera-master:
        container_name: mariadb_master
        image: docker.io/bitnami/mariadb-galera:latest
        ports:
            - '3306:3306'
            - '4444:4444'
            - '4567:4567'
            - '4568:4568'
        volumes:
            - ./data/master:/bitnami/mariadb
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_GALERA_CLUSTER_ADDRESS=yes
            - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
            - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
            - MARIADB_GALERA_CLUSTER_NAME=my_galera
            - MARIADB_GALERA_MARIABACKUP_USER=root
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=password
            - MARIADB_ROOT_PASSWORD=password
            - MARIADB_USER=admin
            - MARIADB_PASSWORD=password
            - MARIADB_DATABASE=my_database
            - MARIADB_REPLICATION_USER=root
            - MARIADB_REPLICATION_PASSWORD=password
        healthcheck:
            test:
                [
                    'CMD',
                    '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh'
                ]
            interval: 15s
            timeout: 5s
            retries: 6
        restart: always
    mariadb-galera-second:
        container_name: mariadb_slave
        image: docker.io/bitnami/mariadb-galera:latest
        ports:
            - '3307:3306'
            - '4445:4444'
            - '4569:4567'
            - '4570:4568'
        volumes:
            - ./data/slave:/bitnami/mariadb
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            # - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_GALERA_CLUSTER_NAME=my_galera
            - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-master:4567,0.0.0.0:4567
            - MARIADB_GALERA_MARIABACKUP_USER=root
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=password
            - MARIADB_ROOT_PASSWORD=password
            - MARIADB_REPLICATION_USER=root
            - MARIADB_REPLICATION_PASSWORD=password
        healthcheck:
            test:
                [
                    'CMD',
                    '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh'
                ]
            interval: 15s
            timeout: 5s
            retries: 6
        restart: always
        depends_on:
            - mariadb-galera-master
# phpmyadmin:
#   image: phpmyadmin
#   restart: always
#   ports:
#     - 8080:80
#   environment:
#     - PMA_ARBITRARY=1

# volumes:
#   mariadb_galera_data:
#     driver: local



#### Add more Containers below ####
# use [ docker network create microservicenetwork ] เพื่อสร้าง mapmagiccloud(your network name) network ขึ้นมาก่อน
networks:
    default:
        external:
            name: microservicenetwork
