version: '3'

services:
  api:
    container_name: Connection
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PW=crudjs
    volumes:
      - ./app/:/app/
      # - /usr/src/app/node_modules
      # command: npm run start:dev
